site_name: "RDC@FRI"
site_url: https://docs.rdc.si
docs_dir: docs
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.expand
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    #- navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
nav:
  - News: index.md
  - FRIDA:
    - About: FRIDA/about.md
    - Access: FRIDA/access.md
    - Slurm: FRIDA/slurm.md
markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - footnotes
  - pymdownx.mark
  - attr_list
  - pymdownx.details

copyright: |
  &copy; 2023 <a href="https://fri.uni-lj.si"  target="_blank" rel="noopener">UL FRI</a>
